# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af649d73d541ea0107b3bd15e7f9dba222f071d1dc0afd42d8d7a9d26e5db5b66ed10421136b432340e41b0523704a276069a3145a6d0b291f0a203eae4b32e2

test:
  secret_key_base: 747b9e476a51745fea5dca866ba13cd28a7f123ea2524e9f6f8fdef6ac103188b55e515dcd50259a3cefc3ac06660ed0d2cd50733020820334c9853622b6a085

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
